### PR TITLE
Translation of "Introduction" chapter

### LINKED ISSUE #1: Introduction
"Issue" to track translation of the `Introduction` Chapter

### PR DESCRIPTION
**Pull request by joaopgrassi**
closes #1

### CODE REVIEW

**Comment by joaopgrassi** [comment]
@nicolastarzia @joao-marcos, I finihsed the "Introduction" chapter, can you please review it? Thanks.

**Comment by nicolastarzia** [comment]
@joaopgrassi, I'll reviewing your translation this week.

**Comment by joaopgrassi** [comment]
Cool, cheers!

**Comment by joaopgrassi** [comment]
Hey @nicolastarzia, any update on this? I would like to merge this this week if possible..

**Pull request merged**
