### PR TITLE
Translation of "Use a database" chapter (#5)

### LINKED ISSUE #5: Use a database
"Issue" to track translation of the `Use a database` Chapter

### PR DESCRIPTION
**Pull request by oliveiramarcio**
closes #5 
@joaopgrassi please review and merge.

This one I did based on pt-br branch.

### CODE REVIEW

**Comment by oliveiramarcio** [comment]
Changed base branch do pt-br.

**Comment by oliveiramarcio** [comment]
@joaopgrassi in this chapter I'm in doubt about the translation of the term "Migrations" referencing to Entity Framework Migrations.

Please, read the translated files during this review and tell me what you think about it.

**Comment by joaopgrassi** [comment]
@oliveiramarcio  I would vote to leave the English term. Translating this into Portuguese will sound weird. This is a technical term related to EF, so let's leave it that way. For also future terms, let's keep the English word whenever we are in doubt.

**Comment by joaopgrassi** [comment]
@oliveiramarcio voce teve tempo para rever meus comentarios? Vamos tentar fechar um MR antes de abrir outro.. pra nao ficarmos perdidos :). Thanks!

**Pull request merged**
